Repository Alok5102R/whichcar, pull requests merged in 2022-10, with the labels that each got.

#6 I'd updated as per requirement.
  page/script.js
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 Updated Car details as per requirement
  page/script.js
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 Updated seat variable and category
  page/script.js
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 Changed color category with seats
  page/choose.html
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 changed code from double quotes to single quotes
  page/choose.html
  page/script.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Improved "choose car" button
  Styles/app.css
  index.html
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 effected the auto sliding of cars in homepage
  Styles/app.css
  index.html
Labels: documentation, enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 Fixed negative range and added placeholder values
  page/choose.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 Disabled car suggestions box
  page/choose.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 added carlinks and ui fixes
  Styles/choose.css
  index.html
  page/choose.html
  page/script.js
Labels: bug, documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 Making navbar sticky
  index.html
  page/choose.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022

#45 improved readme and contributing md
  CONTRIBUTING.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#46 Code sorting and creating separate json to link in js
  Styles/choose.css
  index.html
  page/choose.html
  page/script.js
  utils/cardata.json
  utils/script.js
  utils/style.css
Labels: documentation, hacktoberfest, hacktoberfest2022

#50 removed horizontal scroll bar from homepage and other ui fixes
  index.html
  page/choose.html
  utils/script.js
  utils/style.css
Labels: bug, documentation, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#55 Fixed refresh bug
  utils/script.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#60 Added a dynamic logo with Animation
  img/car-logo.json
  index.html
  page/choose.html
  utils/style.css
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#58 adding tesla models to the json file
  utils/cardata.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022

#63 Added links and new cars
  utils/cardata.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#70 Updated car data between 20L - 30L
  utils/cardata.json
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#73 Created form and linked it.
  page/choose.html
  page/form.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022

#75 Corrected steps
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest2022

#76 Cross browser compatibility
  index.html
  utils/style.css
Labels: bug, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#77 Designed the scrollbar
  utils/style.css
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#80 Added light mode toggle button feature
  index.html
  page/choose.html
  utils/script.js
  utils/style.css
Labels: enhancement, hacktoberfest, hacktoberfest2022

#85 UI fixes for suggestion text and added contact us button
  page/choose.html
  utils/style.css
Labels: bug, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
